#!/usr/bin/env bash

set -e

if [ -d /tmp/git_play ]
then
  rm -rf /tmp/git_play
fi
mkdir -p /tmp/git_play/repo
cd /tmp/git_play/repo
git init --bare --initial-branch main
cd ..
git clone /tmp/git_play/repo /tmp/git_play/bob
cd /tmp/git_play/bob
touch foo
git add .
git commit -m'initial commit'
git push -u origin main
git clone /tmp/git_play/repo /tmp/git_play/alice
