resources:
- name: presentations
  type: git
  icon: github
  source:
    uri: https://github.com/scottmuc/presentations
    branch: main

- name: bootstrapped-skopeo
  type: registry-image
  icon: docker
  source:
    repository: zot.scottmuc.com/skopeo
    tag: latest


- name: cachix-flakes
  type: registry-image
  icon: docker
  source:
    repository: zot.scottmuc.com/cachix-flakes
    tag: latest


- name: presentations-ci
  type: registry-image
  icon: docker
  source:
    repository: zot.scottmuc.com/presentations-ci
    tag: latest

jobs:
- name: build-presentations-ci-image
  public: true

  plan:
  - get: presentations
  - get: bootstrapped-skopeo
  - get: cachix-flakes

  - task: build-presentations-ci-image
    image: cachix-flakes
    config:
      platform: linux
      inputs:
      - name: presentations
      outputs:
      - name: result
      run:
        path: sh
        args:
          - -c
          - |
            cachix use scottmuc

            cachix watch-exec scottmuc -- \
              nix --extra-experimental-features "nix-command flakes" \
              build ./presentations/git-workshop#ci-image -o result/image
              # Create a local filesystem reference because /nix/store
              # doesn't persist across steps.
              cp result/image result/image.tar.gz
              (cd result && gunzip image.tar.gz)
      params:
        CACHIX_AUTH_TOKEN: ((nix.cachix_token))

  - task: convert-and-push-presentations-ci
    image: bootstrapped-skopeo
    config:
      platform: linux
      inputs:
      - name: result
      outputs:
      - name: converted
      run:
        path: skopeo
        args:
          - copy
          - --format=oci
          - docker-archive:result/image.tar
          - oci:converted/oci

  - put: presentations-ci
    params:
      image: converted/oci


- name: static-analysis
  public: true

  plan:
  - get: presentations-ci
    passed: [build-presentations-ci-image]
    trigger: true
  - get: presentations
    trigger: true

  - across:
    - var: script
      values:
      - bin/nix-checks.sh
      - bin/shell-checks.sh
    task: running-((.:script))
    image: presentations-ci
    config:
      platform: linux
      inputs:
      - name: presentations
      run:
        path: bin/cachix-ci-nix-wrapper.sh
        dir: presentations
        args:
          - "((.:script))"


- name: git-workshop
  public: true

  plan:
  - get: presentations-ci
    passed: [build-presentations-ci-image]
    trigger: true
  - get: presentations
    trigger: true

  - task: running-git-workshop-tests
    image: presentations-ci
    config:
      platform: linux
      inputs:
      - name: presentations
      run:
        path: ../bin/cachix-ci-nix-wrapper.sh
        dir: presentations/git-workshop
        args:
          - ./test.sh
      params:
        GIT_AUTHOR_NAME: test
        GIT_AUTHOR_EMAIL: test@example.com
        GIT_COMMITTER_NAME: test
        GIT_COMMITTER_EMAIL: test@example.com
