name: Git Workshop CI
on:
  workflow_dispatch:
  push:
    paths:
    - 'git-workshop/**'
    - '.github/workflows/git-workshop-ci.yml'


jobs:
  behave-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      # We need a python, but we know there already exists a version from the
      # the base image provided by GitHub:
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
      #
      # We can also see pip and pip3 are installed. We only need to install virtualenv to
      # satisfy all the requirements of the ./test.sh script
      - name: Install virtualenv
        run: pip3 install virtualenv

      - name: Run the tests
        working-directory: ./git-workshop
        # https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables
        env:
          GIT_AUTHOR_NAME: "GHA Workflow"
          GIT_COMMITTER_NAME: "GHA Workflow"
          EMAIL: "gha@example.com"
        run: ./test.sh

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Auth with container registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: scottmuc

      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          context: ./git-workshop
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/scottmuc/handsongit:latest
